Adding taxdump format and taxdump-to-tree converter
biocore/scikit-bio pull request #1810
Opened 2022-04-19 23:54 UTC by qiyunzhu

Per discussion with @wasade , I created this format, parser and converter. It is useful for reading NCBI taxonomy database (`taxdump`) into data frames and convert them into a phylogenetic tree (`skbio.TreeNode`). It is potentially useful for level-flexible classification of microbiome data.

This functionality was inspired by a similar function implemented by me in Woltka: https://github.com/qiyunzhu/woltka. In developing the current PR, I re-wrote the code in a way that is coherent with scikit-bio standards.

Please complete the following checklist:

* [x] I have read the guidelines in [CONTRIBUTING.md](https://github.com/biocore/scikit-bio/blob/master/CONTRIBUTING.md).

* [x] I have documented all public-facing changes in [CHANGELOG.md](https://github.com/biocore/scikit-bio/blob/master/CHANGELOG.md).

* [ ] **This pull request includes code, documentation, or other content derived from external source(s).** If this is the case, ensure the external source's license is compatible with scikit-bio's [license](https://github.com/biocore/scikit-bio/blob/master/COPYING.txt). Include the license in the `licenses` directory and add a comment in the code giving proper attribution. Ensure any other requirements set forth by the license and/or author are satisfied. **It is your responsibility to disclose code, documentation, or other content derived from external source(s).** If you have questions about whether something can be included in the project or how to give proper attribution, include those questions in your pull request and a reviewer will assist you.

* [ ] **This pull request does not include code, documentation, or other content derived from external source(s).**

**Note:** [REVIEWING.md](https://github.com/biocore/scikit-bio/blob/master/REVIEWING.md) may also be helpful to see some of the things code reviewers will be verifying when reviewing your pull request.

2022-04-20 00:05 UTC, wasade requested changes
This seems reasonable but would it be possible to not include the changes to the .c files?

2022-04-20 00:05 UTC, wasade commented on skbio/tree/_tree.py
> +            ~(nodes.index == root_id)].groupby('parent_tax_id')}
```suggestion
            nodes.index != root_id].groupby('parent_tax_id')}
```

2022-04-20 00:10 UTC, qiyunzhu commented
@wasade I didn't touch the .c files. Perhaps the changes happen automatically when I ran unit tests? Do you know how to fix?

> This seems reasonable but would it be possible to not include the changes to the .c files?

2022-04-20 00:13 UTC, qiyunzhu commented
> @wasade I didn't touch the .c files. Perhaps the changes happen automatically when I ran unit tests? Do you know how to fix?
> 
> > This seems reasonable but would it be possible to not include the changes to the .c files?

Manually fixed. No worry.

2022-04-20 00:58 UTC, wasade approved these changes

2022-04-20 20:57 UTC, wasade commented
@qiyunzhu, I'm +1 on this. Could you add a mention in the changelog? We can merge after

2022-04-21 02:32 UTC, qiyunzhu commented
@wasade Thanks! Changelog edited.

2022-04-23 01:19 UTC, wasade commented on CHANGELOG.md
> +## Version 0.5.8
```suggestion
## Version 0.5.8-dev
```

2022-04-23 01:19 UTC, wasade commented
Thanks!!

2022-04-23 01:20 UTC, merged